[server]

# Automatically rerun script when the file is modified on disk.
runOnSave = false

# The port where the server will listen for browser connections.
port = 8501

# The base path for the URL where Streamlit should be served from.
baseUrlPath = ""

# Enables support for Cross-Origin Request Sharing (CORS) protection, for added security.
# Due to conflicts between CORS and XSRF, if `server.enableXsrfProtection` is on and `server.enableCORS` is off at the same time, we will prioritize `server.enableXsrfProtection`.
enableCORS = true

# Max size, in megabytes, for files uploaded with the file_uploader.
maxUploadSize = 200

# Max size, in megabytes, of messages that can be sent via the WebSocket connection.
maxMessageSize = 200

# Enables support for websocket compression.
enableWebsocketCompression = false

# Enable serving files from a `static` directory in the running app's directory.
enableStaticServing = false

[browser]

# Whether to send usage statistics to Streamlit.
gatherUsageStats = false

[deprecation]

# Set to false to disable the deprecation warning for the file uploader encoding.
showfileUploaderEncoding = true

[logger]

# Level of logging: 'error', 'warning', 'info', or 'debug'.
# Default: 'info'
level = "info"

# String format for logging messages. If logger.datetimeFormat is set, logger messages will default to `%(asctime)s.%(msecs)03d %(message)s`. See [Python's documentation](https://docs.python.org/2.6/library/logging.html#formatter-objects) for available attributes.
# Default: "%(asctime)s %(message)s"
messageFormat = "\n%(asctime)s [%(levelname)s] %(message)s"
