version: "3"

x-solr-service: &solr-service
  image: solr:9.1.1
  environment:
    ZK_HOST: zookeeper2:3181
  depends_on:
    - zookeeper2
  volumes:
    - "./solr/solr.in.sh:/etc/default/solr.in.sh"
    - "./solr/conf/basic2_conf:/opt/solr/server/solr/configsets/basic2/conf"
    - "./solr/conf/mini_dual_conf:/opt/solr/server/solr/configsets/mini_dual/conf"
    - "./solr/logs:/var/solr/logs"

x-zookeeper-service: &zookeeper-service
  image: zookeeper:3.7
  container_name: zookeeper2
  environment:
    ZOO_MY_ID: 2
    ZOO_SERVERS: server.2=zookeeper2:2888:3888;2181
    ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok

x-app-service: &app-service
  build: ./python/
  container_name: app2
  volumes:
    - ./python:/workspace/app
    - ./python/logs:/var/log/app
  working_dir: /workspace/app
  command: "streamlit run app.py --logger.level=info 2> streamlit_logs.log"
  links:
    - solr_node2
    - zookeeper2
  ports:
    - 8502:8501

services:
  solr_node2:
    <<: *solr-service
    container_name: solr_node2
    ports:
      - "8984:8983"
      - "9855:9854"
  zookeeper2:
    <<: *zookeeper-service
  app2:
    <<: *app-service
